export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';

export const ADDRESS_BOOK_ADD = 'ADDRESS_BOOK_ADD';
export const ADDRESS_BOOK_EDIT = 'ADDRESS_BOOK_EDIT';
export const ADDRESS_BOOK_DELETE = 'ADDRESS_BOOK_DELETE';
