export const CONTACT_BOOK_ADD = 'CONTACT_BOOK_ADD';
export const CONTACT_BOOK_EDIT = 'CONTACT_BOOK_EDIT';
export const CONTACT_BOOK_DELETE = 'CONTACT_BOOK_DELETE';
export const CONTACT_BOOK_SEARCH = 'CONTACT_BOOK_SEARCH';
